spring.application.name=ev-battery-health

# PostgreSQL - Local Database
spring.datasource.url=jdbc:postgresql://localhost:5432/EVCharging
spring.datasource.username=postgres
spring.datasource.password=Prateek@123
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL - Railway (Uncomment when deploying to Railway)
# spring.datasource.url=jdbc:postgresql://postgres:password@hostname:5432/railway

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Server
server.port=${PORT:8080}

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prateek2222kumar@gmail.com
spring.mail.password=wvmb nvwo grqz ervh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true